name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد پروژه
        uses: actions/checkout@v4

      - name: نصب Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: ساخت پروژه Flutter
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create --project-name modiriat_hesabha --platforms=android .
          fi

      - name: ذخیره فایل‌های Flutter در GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "ایجاد پروژه Flutter"
            git push
          fi

      - name: نصب وابستگی‌ها
        run: flutter pub get

      - name: ساخت APK نسخه Release
        run: flutter build apk --release

      - name: آماده‌سازی APK برای دانلود
        uses: actions/upload-artifact@v4
        with:
          name: modiriat-hesabha-apk
          path: build/app/outputs/flutter-apk/app-release.apk
